name: 'RegEx Issue Checker'
description: 'Labels and comments to issues automatically based on their body'
author: 'zzyyyl'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description: 'Path to the labeler.yml configuration file'
    required: true
  not-before:
    description: 'Is optional and will result in any issues prior to this timestamp to be ignored'
    required: false
  include-title:
    description: 'Include the title in addition to the body in the regex target'
    required: false
    default: "0"
  sync-labels:
    description: 'Remove labels from issue if regex does not match'
    required: false
    default: 1
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
